### ISSUE TITLE
Class not found Exception in XML

### ISSUE THREAD

**Issue by VirajShirwalkar** [mars885/persistent-search-view#42]
Hi your library does not loading a class as shared below. Please resolve this asap.
**The following classes could not be instantiated:
- com.paulrybitskyi.persistentsearchview.PersistentSearchView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.ClassNotFoundException: com.arthurivanets.adapster.listeners.OnItemClickListener**

java.lang.ClassNotFoundException: com.arthurivanets.adapster.listeners.OnItemClickListener
	at com.android.tools.idea.rendering.classloading.loaders.DelegatingClassLoader.findClass(DelegatingClassLoader.kt:81)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.android.tools.idea.rendering.classloading.loaders.DelegatingClassLoader.loadClass(DelegatingClassLoader.kt:65)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:282)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Target sdk 32
Min sdk 21
AndroidX
Java - Android Studio

While building a project it says,
*** What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebugAndroidTest'.
> Could not resolve all files for configuration ':app:debugAndroidTestCompileClasspath'.
   > Could not find com.arthurivanets.adapster:adapster:1.0.13.
     Required by:
         project :app > com.paulrybitskyi.persistentsearchview:persistentsearchview:1.1.4**

**Comment by VirajShirwalkar** [comment]
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthurivanets.adapster:adapster:1.0.13.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/arthurivanets/adapster/adapster/1.0.13/adapster-1.0.13.pom
       - https://repo.maven.apache.org/maven2/com/arthurivanets/adapster/adapster/1.0.13/adapster-1.0.13.pom
       - https://jitpack.io/com/arthurivanets/adapster/adapster/1.0.13/adapster-1.0.13.pom
     Required by:
         project :app > com.paulrybitskyi.persistentsearchview:persistentsearchview:1.1.4

**Comment by mars885** [comment]
Hey.

The only solution to this problem is to declare `jcenter()` in the list of repositories because of the `adapster` dependency that is available only on the JCenter.
